edition="2021"

newline_style="Auto"
fn_params_layout="Vertical"
use_small_heuristics="Default"
match_arm_leading_pipes="Never"

tab_spaces=4
max_width=120
array_width=60
chain_width=60
fn_call_width=60
attr_fn_like_width=70
struct_variant_width=50
single_line_if_else_max_width=50
single_line_let_else_max_width=50
short_array_element_width_threshold=10

hard_tabs=true
merge_derives=true
reorder_imports=true
reorder_modules=true
use_try_shorthand=true
force_explicit_abi=true
remove_nested_parens=true
disable_all_formatting=false
use_field_init_shorthand=true
match_block_trailing_comma=true
